# Generated by Django 5.1 on 2026-02-25 11:33
# Generated by Django 5.1 on 2026-02-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superAdmin', '0003_deliveryagentapprovallog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagentapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='vendorapprovallog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
