# Generated by Django 6.0.2 on 2026-02-18 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0003_alter_deliveryagentprofile_id_number_and_more'),
        ('user', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='deliveryAgent.deliveryagentprofile'),
        ),
    ]
