# Generated by Django 6.0.1 on 2026-02-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_review_updated_at_review_reviewer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Calculated commission amount', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Commission % at time of purchase', max_digits=5),
        ),
    ]
