# Generated by Django 6.0.1 on 2026-02-20 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_order_deductions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='deductions',
        ),
    ]
