# Generated by Django 6.0.2 on 2026-02-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_authuser_username_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
