# Generated by Django 6.0.2 on 2026-02-24 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_authuser_gender'),
        ('vendor', '0011_product_average_rating_product_total_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('Product', 'user')},
        ),
    ]
