# Generated by Django 5.1 on 2026-02-25 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_address_id_alter_authuser_id_alter_cart_id_and_more'),
        ('user', '0014_orderreturn_condition_notes_orderreturn_pickup_agent_and_more'),
    ]

    operations = [
    ]
