# Generated by Django 6.0.2 on 2026-02-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0009_deliveryassignment_assignment_type_and_more'),
        ('user', '0013_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreturn',
            name='condition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='pickup_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_pickups', to='deliveryAgent.deliveryagentprofile'),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderreturn',
            name='verification_images',
            field=models.ImageField(blank=True, null=True, upload_to='return_verification/'),
        ),
        migrations.AlterField(
            model_name='orderreturn',
            name='status',
            field=models.CharField(choices=[('requested', 'Return Requested'), ('approved', 'Return Approved'), ('pickup_assigned', 'Pickup Assigned'), ('picked_up', 'Picked Up'), ('received', 'Received/Verified'), ('completed', 'Refund Processed'), ('rejected', 'Return Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
