# Generated by Django 6.0.1 on 2026-02-19 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0005_orderitem_commission_amount_and_more'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_kitchen', 'Home & Kitchen'), ('beauty_personal_care', 'Beauty & Personal Care'), ('sports_fitness', 'Sports & Fitness'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('books', 'Books'), ('services', 'Services'), ('other', 'Other')], max_length=50, unique=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('hybrid', 'Hybrid')], default='percentage', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_details_snapshot', models.JSONField(help_text='Snapshot of bank details at time of payout')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='vendor.vendorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('entry_type', models.CharField(choices=[('REVENUE', 'Order Revenue'), ('COMMISSION', 'Platform Commission'), ('REFUND', 'Customer Refund'), ('PAYOUT', 'Vendor Payout'), ('CANCELLATION', 'Order Cancellation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.orderitem')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ledger_entries', to='vendor.vendorprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['vendor', 'is_settled'], name='finance_led_vendor__d65c14_idx'), models.Index(fields=['settlement_date'], name='finance_led_settlem_12cbda_idx'), models.Index(fields=['reference_id'], name='finance_led_referen_749548_idx')],
            },
        ),
    ]
