# Generated by Django 5.1 on 2026-02-25 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('electronics', 'Electronics'), ('fashion', 'Fashion'), ('home_kitchen', 'Home & Kitchen'), ('beauty_personal_care', 'Beauty & Personal Care'), ('sports_fitness', 'Sports & Fitness'), ('toys_games', 'Toys & Games'), ('automotive', 'Automotive'), ('grocery', 'Grocery'), ('books', 'Books'), ('services', 'Services'), ('other', 'Other')], max_length=50, unique=True)),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed'), ('hybrid', 'Hybrid')], default='percentage', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed')], default='percentage', max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Global Commission',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('commission_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('entry_type', models.CharField(choices=[('REVENUE', 'Order Revenue'), ('COMMISSION', 'Platform Commission'), ('REFUND', 'Customer Refund'), ('PAYOUT', 'Vendor Payout'), ('CANCELLATION', 'Order Cancellation')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_settled', models.BooleanField(default=False)),
                ('settlement_date', models.DateTimeField(blank=True, null=True)),
                ('reference_id', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('bank_details_snapshot', models.JSONField(help_text='Snapshot of bank details at time of payout')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
