# Generated by Django 5.1 on 2026-02-25 23:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('user', '0001_initial'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.order'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='order_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.orderitem'),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_ledger_entries', to='vendor.vendorprofile'),
        ),
        migrations.AddField(
            model_name='payout',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payout_history', to='vendor.vendorprofile'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['vendor', 'is_settled'], name='finance_led_vendor__d65c14_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['settlement_date'], name='finance_led_settlem_12cbda_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['reference_id'], name='finance_led_referen_749548_idx'),
        ),
    ]
