# Generated by Django 6.0.1 on 2026-02-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_globalcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgerentry',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ledgerentry',
            name='net_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
