# Generated by Django 6.0.2 on 2026-02-24 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0008_account_deletion_and_docs'),
        ('user', '0013_alter_review_options_review_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='assignment_type',
            field=models.CharField(choices=[('delivery', 'Standard Delivery'), ('return', 'Return Pickup')], default='delivery', max_length=10),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='return_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_assignments', to='user.orderreturn'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_assignments', to='user.order'),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Location'), ('attempting_delivery', 'Attempting Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='assigned', max_length=30),
        ),
    ]
