# Generated by Django 5.2 on 2026-02-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='id_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='id_proof_file',
            field=models.FileField(blank=True, null=True, upload_to='id_proofs/'),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='id_type',
            field=models.CharField(choices=[('aadhar', 'Aadhar'), ('passport', 'Passport'), ('pan', 'PAN'), ('drivers_license', "Driver's License")], default='aadhar', max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='license_expires',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='license_file',
            field=models.FileField(blank=True, null=True, upload_to='license_docs/'),
        ),
        migrations.AlterField(
            model_name='deliveryagentprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
