# Generated by Django 6.0.1 on 2026-02-20 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0003_alter_deliveryagentprofile_id_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='service_pincodes',
            field=models.JSONField(default=list, help_text='List of specific pincodes/areas served'),
        ),
    ]
