# Generated by Django 6.0.2 on 2026-02-21 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0005_deliveryagentprofile_last_location_update_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverydailystats',
            name='completed_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverydailystats',
            name='distance_covered',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deliverydailystats',
            name='failed_deliveries',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deliverydailystats',
            name='hours_worked',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deliverydailystats',
            name='total_deliveries',
            field=models.IntegerField(default=0),
        ),
    ]
