# Generated by Django 6.0.2 on 2026-02-21 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0006_deliverydailystats_completed_deliveries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryassignment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Location'), ('attempting_delivery', 'Attempting Delivery'), ('delivered', 'Delivered'), ('failed', 'Delivery Failed'), ('cancelled', 'Cancelled')], default='assigned', max_length=30),
        ),
    ]
