# Generated by Django 6.0.2 on 2026-02-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0007_deliveryassignment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='aadhar_card_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_aadhar_cards/'),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='additional_documents',
            field=models.FileField(blank=True, null=True, upload_to='delivery_additional_docs/'),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='deletion_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='deletion_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='is_deletion_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='pan_card_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_pan_cards/'),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='deliveryagentprofile',
            name='selfie_with_id',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_selfies/'),
        ),
    ]
