# Generated by Django 5.1 on 2026-02-25 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryAgent', '0009_alter_deliveryagentperformance_id_and_more'),
        ('deliveryAgent', '0009_deliveryassignment_assignment_type_and_more'),
    ]

    operations = [
    ]
